#!/bin/bash

# Validate your manifests (generated by Kustomize) upon Kubernetes API
# You need to install kubernetes-validate:
# pip install kubernetes-validate

# Validate on this specific version:
KUBE_VERSION=1.18.0

which kubernetes-validate &> /dev/null || { echo "Please install kubernetes-validate with 'pip install kubernetes-validate'"; exit 1;}

TMPDIR=$(mktemp -d)

overlays=($(ls overlays))

for overlay in ${overlays[@]}
do
    MANIFEST_FILE=${TMPDIR}/manifest-$overlay.yaml

    kustomize build overlays/$overlay > ${MANIFEST_FILE}
    [ "$?" -eq "0" ] || { echo "error during kustomize build overlays/$overlay"; exit 1; }

    kubernetes-validate -k $KUBE_VERSION --strict ${MANIFEST_FILE} 2>/dev/null | \
        grep -v ^INFO && { echo "error during kubernetes-validate ${MANIFEST_FILE}"; exit 2; }
    
    echo "kustomize config for overlays/$overlay - ok"
done

rm -rf ${TMPDIR}
